### ISSUE TITLE
AddResults endpoint

### ISSUE THREAD

**Issue by Aemilivs** [zoosk/testrail-client#49]
There is [a limitation for amount of requests](http://docs.gurock.com/testrail-api2/errors?s%5B%5D=429) that can be fired to TR per minute
TR API will refuse to accept any more requests after the limit is reached until the minute passes
Support of the [AddResults](http://docs.gurock.com/testrail-api2/reference-results#add_results) and [AddResultsForCases](http://docs.gurock.com/testrail-api2/reference-results#add_results_for_cases) solves this issue

**Comment by gozegoabhayr** [comment]
Can you please elaborate this line Support of the AddResults and AddResultsForCases solves this issue?

**Comment by MaximeBrodeur** [comment]
I would like the support for AddResults and AddResultsForCase as well.

This solve the limitation issue because we can then batch push all test results with a single call instead of one call per test. This is particularly useful when reporting status for short running tests like unit tests or integration tests.
